### ISSUE TITLE
Migration from Catch2 v2 to v3?

### ISSUE THREAD

**Issue by XzoRit** [copperspice/cs_libguarded#26]
Hi and thanks for this really interesting library.

While playing around with it locally the tests would not build because I was using Catch2 v3.
I was able to make it compile, link and run the tests successfully with just a few little changes:
[How to migrate projects from v2 to v3](https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#how-to-migrate-projects-from-v2-to-v3)

If you are interested I would be happy to create a pull request for supporting Catch2 v3.

**Comment by agserm** [comment]
Thanks for reporting this, and I'm glad you found the library interesting.

We want to stay with Catch2 v2 since it is header only. We think the best way to resolve the issue you brought up is to embed the Catch2 header with cs_libguarded as we have done in several of our other libraries. These are minor changes and they should be pushed shortly.

**Comment by XzoRit** [comment]
Great.
Sounds like a plan :smile: .
